### ISSUE TITLE
不能读取PSM记录

### ISSUE THREAD

**Issue by sd361541453** [MiEcosystem/mijia_ble#10]
蓝牙芯片：NRF52832-QFAA
开发环境，Keil MDK V5.24.1
SDK环境：NRF_SDK_15.20
LIB文件：mijia_std_authen_keil_nrf_1_1_4_752fc700.lib
下载命令: git clone -b Nordic_SDK15.2 --recursive https://github.com/MiEcosystem/mijia_ble.git
![image](https://user-images.githubusercontent.com/12649744/57185549-17b60a00-6f00-11e9-9deb-ecd84749e92c.png)

**Comment by TuChucheng** [comment]
这个是正常的，一开始flash里面没有内容，就是读不到内容

**Comment by TuChucheng** [comment]
后面的connect不成功是怎么操作的？

**Comment by sd361541453** [comment]
当时应该是用开发版米家APP连接,不是每次都出现的.后来试了几次都不能复现. 不过按下按键也是会有Fatal Error,不知道是不是一个原因.

**Comment by TuChucheng** [comment]
Fatal error是应用层报出来的，和米家认证库无关。
可以在示例工程的编译选项中加上DEBUG，查看详细的出错信息，而不是简单的"Fatal error"了。
