### ISSUE TITLE
如何实现米家APP交互的命令实现

### ISSUE THREAD

**Issue by yangkai-menuo** [MiEcosystem/mijia_ble#11]
1，如果想接受米家APP下发命令的实现，BLE设备如果在mijiable 上面实现 ，另外什么是长连接；

2，如果实现BLE设备属性的状态广播？比如电池的电量 | 0x100A，如何填充
是否可以指出在demo库中具体实现的例子？

**Comment by TuChucheng** [comment]
此demo只实现与米家APP间的认证，即可连入米家APP；后续的交互问题，若有实际的产品，可联系小米产品经理安排支持。

**Comment by yangkai-menuo** [comment]
多谢
