### ISSUE TITLE
DA14585 SDK 编译时出现多个失败

### ISSUE THREAD

**Issue by yangkai-menuo** [MiEcosystem/mijia_ble#12]
编译存在以下几个问题，建议的SDK_6.0.6.427官方无法下载到，目前采用
SDK版本：6.0.8.509
LIB版本： DA14585_1_1_4_752
芯片模组：DA14585

**编译失败1现象：**
..\..\..\..\..\..\..\..\..\sdk\platform\arch\arch.h(116): error:  #29: expected an expression
  #if ((CFG_TRNG == 32) || (CFG_TRNG == 64) || (CFG_TRNG == 128) || (CFG_TRNG == 256) || (CFG_TRNG == 512)  || (CFG_TRNG == 1024)) && (!FPGA)
临时解决方法：
da1458x_config_advanced.h
#define CFG_TRNG  32

**编译失败2现象：**
.\..\src\config\user_config.h(219): error:  #136: struct "gapm_configuration"  has no field "priv1_2"
     .priv1_2 = 0,
临时解决方法：
user_config.h
删除"    .priv1_2 = 0," 

**编译失败3现象：**
..\..\..\..\..\libs\mible_app_authen\mible_server.h(94): error:  #101: "device_info" has already been declared in the current scope
  } device_info;
待解决

**编译失败4现象：**
..\..\..\portable\sdk_overwriter\app_default_handlers.c(202): error:  #147-D: declaration is incompatible with "void default_app_on_set_dev_info(const struct gapc_set_dev_info_req_ind *, uint8_t *)"  (declared at line 206 of "..\..\..\..\..\..\..\..\..\sdk\app_modules\api\app_default_handlers.h")
待解决

**编译失败5现象：**
..\..\..\portable\sdk_overwriter\app_default_handlers.c(434): error:  #120: return value type does not match the function type
待解决

**Comment by TuChucheng** [comment]
SDK_6.0.6.427可向Dialog原厂技术支持申请。
SDK_6.0.8.509若有产品需求，我们也可安排进行SDK升级。

**Comment by yangkai-menuo** [comment]
多谢解答
我们已经拿到SDK_6.0.6.427，暂时我先基于此sdk开发
