### ISSUE TITLE
如何上报数据,实现产品功能

### ISSUE THREAD

**Issue by sd361541453** [MiEcosystem/mijia_ble#13]
我在产品功能里面定义的属性（Property）方法（Method）事件（Event）,请问如何在固件端实现相应的功能呢? 需要调用哪些函数? 或者有没有这方面的文档. 这些又如何转成MIBeacon的Object.

**Comment by TuChucheng** [comment]
https://iot.mi.com/new/guide.html?file=04-%E5%B5%8C%E5%85%A5%E5%BC%8F%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97/06-BLE%E4%BA%A7%E5%93%81%E6%8E%A5%E5%85%A5/03-%E7%B1%B3%E5%AE%B6BLE%E5%B9%BF%E6%92%AD%E5%8D%8F%E8%AE%AE

小米IoT开发者平台中有MiBeacon协议介绍
