### ISSUE TITLE
设备使用米家APP能扫描和连接，但不能绑定成功

### ISSUE THREAD

**Issue by alex0824li** [MiEcosystem/mijia_ble#14]
1、使用平台：nRF52832
2、lib库：mijia_std_authen_keil_nrf_1_1_4_752fc700.lib
3、详细问题：我将此lib文件添加到此demo工程中，pid使用1329，使用米家APP能扫描和连接，但不能绑定成功，使用sniffer抓包，数据见附件，问题现象为在NO593行记录发送了写请求，但未收到设备的notification数据。
[ERROR.zip](https://github.com/MiEcosystem/mijia_ble/files/3190846/ERROR.zip)

**Comment by TuChucheng** [comment]
改了pid可能需要app端的配合，就不大好定位。
你可以先不改pid试试看，在app端就是显示产品名为小米蓝牙开发板，先用这个调试看看。
先定位到问题到底是在那一边。

**Comment by alex0824li** [comment]
我个人认为应该跟pid没有关系，因为我们公司很早之前有一个产品是另外一个平台的，我将这个pid修改到那个代码里面去是可以完成绑定这个过程的。见这个附件

[OK.zip](https://github.com/MiEcosystem/mijia_ble/files/3196853/OK.zip)

**Comment by TuChucheng** [comment]
什么都不改，就使用下载的原始例程，能够完成绑定过程吗？

**Comment by alex0824li** [comment]
使用原始的例程是不能运行的

**Comment by TuChucheng** [comment]
确认一下你下载的分支和你本地的SDK，应该使用Nordic 15.2分支和SDK，注意和Nordic分支区分
