### ISSUE TITLE
如何才能让蓝牙网关设备检测到

### ISSUE THREAD

**Issue by sd361541453** [MiEcosystem/mijia_ble#15]
我已经申请了设备联动, 然后也发送了object包, 手机可以进行绑定, 还是不能被蓝牙网关检测到.
![image](https://user-images.githubusercontent.com/12649744/57988653-626c8000-7ac3-11e9-837c-3d199506c881.png)
![image](https://user-images.githubusercontent.com/12649744/57988679-c000cc80-7ac3-11e9-913c-e50fd16dd95b.png)

**Comment by TuChucheng** [comment]
设备和网关要在同一账号下，而且新绑定设备在网关上显示上线是需要一段时间的。

**Comment by sd361541453** [comment]
> 设备和网关要在同一账号下，而且新绑定设备在网关上显示上线是需要一段时间的。

是在同一账号下面的, 等了比较长时间都没有检测到, 是不是需要服务器那边通过才可以上报啊, 可以帮我查询一下么(pid:0x04E1). 温度计是可以正常提醒的. 我网关固件是最新的. 尝试重启过网关. 
![image](https://user-images.githubusercontent.com/12649744/57996492-551eb800-7afa-11e9-8f6a-296a5a942c4d.png)
![image](https://user-images.githubusercontent.com/12649744/57996497-623ba700-7afa-11e9-86f1-47519f270f24.png)

**Comment by TuChucheng** [comment]
大致时间说一下，你的uid说一下

**Comment by sd361541453** [comment]
424881015，，大概不绑定了3天，解除绑定后又等了4个小时。

**Comment by TuChucheng** [comment]
1、说一下你出现这个问题的时间，哪天哪个小时？我查一下网关的log信息。
2、你的网关名称就是“音箱”是吧？

**Comment by sd361541453** [comment]
1.问题其实没有个具体时间, 温度计和mesh射灯和我要调试的产品都是在蓝牙网关附近的. 已经在附近也绑定了同一个账号,然后5月10号开始就一直放在一起的. 然后蓝牙网关界面只能找到其中温度计和mesh射灯,找不到我调试的设备.
2.是的.

**Comment by TuChucheng** [comment]
直接找对接的产品经理安排技术支持吧，这里沟通效率太低

**Comment by sd361541453** [comment]
ok,现在可以了, 申请需要周二晚上12点生效.
