### ISSUE TITLE
接入米家协议不能修改广播地址？

### ISSUE THREAD

**Issue by alex0824li** [MiEcosystem/mijia_ble#16]
我在官方的SDK15.2的事例工程添加入lib之后，不修改MAC地址是可以连接上的，但是我添加了修改MAC地址功能之后就不能正常绑定和连接了
修改代码见如下// Add code start........ // Add code end之间的代码：
static void advertising_init(void)
{
    MI_LOG_INFO("advertising init...\n");
    mibeacon_frame_ctrl_t frame_ctrl = {
    .time_protocol = 0,
    .is_encrypt = 0,
    .mac_include = 1,
    .cap_include = 1,
    .obj_include = 0,
    .bond_confirm = 0,
    .version = 0x03,
    };
    mibeacon_capability_t cap = {.connectable = 1,
                                .encryptable = 1,
                                .bondAbility = 1};

    mible_addr_t dev_mac;
    
    // Add code start
    ble_gap_addr_t mac_addr_tmp;          
    mac_addr_tmp.addr_type = 0;                           
    for(uint8_t i = 0; i < 6; i ++) 
    {
        mac_addr_tmp.addr[i] = i + 0x31;
    }
    uint32_t err_code = sd_ble_gap_addr_set(&mac_addr_tmp);
    APP_ERROR_CHECK(err_code);  
    // Add code end
    
    mible_gap_address_get(dev_mac);
    
    mibeacon_config_t mibeacon_cfg = {
    .frame_ctrl = frame_ctrl,
    .pid =dev_info.pid,
    .p_mac = (mible_addr_t*)dev_mac, 
    .p_capability = &cap,
    .p_obj = NULL,
    };
    
    uint8_t service_data[31];
    uint8_t service_data_len=0;
    
    if(MI_SUCCESS != mible_service_data_set(&mibeacon_cfg, service_data, &service_data_len)){
        MI_LOG_ERROR("mibeacon_data_set failed. \r\n");
        return;
    }
    
    uint8_t adv_data[23]={0};
    uint8_t adv_len=0;
    // add flags
    adv_data[0] = 0x02;
    adv_data[1] = 0x01;
    adv_data[2] = 0x06;
    
    memcpy(adv_data+3, service_data, service_data_len);
    adv_len = service_data_len + 3;
    mible_gap_adv_data_set(adv_data,adv_len,NULL,0);

    MI_LOG_INFO("adv mi service data:");
    MI_LOG_HEXDUMP(adv_data, adv_len);
    MI_PRINTF("\r\n");
    return;
}

**Comment by TuChucheng** [comment]
修改MAC地址的地方要在更早的初始化时候，可以试试在boards.c文件的bsp_board_init函数中修改地址

**Comment by alex0824li** [comment]
现在按照你的指导，是可以修改MAC地址了，但是一旦断开就不会再广播了

**Comment by TuChucheng** [comment]
这个问题，你看看是不是引入了其它的改动。
在mible_disconnected函数中是会调用advertising_start，重新开启广播。你调试看看断开连接之后这地方执行没有？

**Comment by alex0824li** [comment]
我现在最新的异常情况是：我正常修改MAC地址了，修改后也能正常广播，但是使用米家APP连接会出现连接上很快又再次断开，Wireshark抓取到的连接过程见附件，lib版本是mijia_std_authen_keil_nrf_1_1_4_752fc700.lib，测试工程是贵司官方提供的事例工程，Keil版本是V5.27

main函数中的部分代码如下：
    power_management_init();
    ble_stack_init();
    gap_params_init();
    gatt_init();
    cod_mac_addr_init();    // Change the advertising addr ...
    time_init(NULL);
    buttons_leds_init(&erase_bonds);  
    conn_params_init();
    mible_std_auth_evt_register(std_authen_event_cb);
    /* <!> mible_record_create() must be called after ble_stack_init(). */
    mible_record_create(0xBEEF,0);
    services_init();
[error.zip](https://github.com/MiEcosystem/mijia_ble/files/3320457/error.zip)

**Comment by TuChucheng** [comment]
修改mac地址后再连米家APP，确实没试过这样操作，我找时间研究验证一下

**Comment by TuChucheng** [comment]
不知道你是怎样改的地址？如上所述，我在board.c文件的bsp_board_init函数中修改地址，将CC:XXXX改为了4C:XXXX，即将一个Static Device Address改为了Public Device Address，测试是可以正常连接也并未断开。不清楚你是怎样操作的？或者是把地址改为了什么？

**Comment by alex0824li** [comment]
cod_mac_addr_init()的实现如下：
/**@brief Function for initializing the Advertising functionality.
 */
int8_t cod_mac_addr_set(const uint8_t * pu8SrcAddr)
{
	int8_t ret_code;
	ret_code_t err_code;
	ble_gap_addr_t mac_addr;

	if(pu8SrcAddr != NULL)
	{
		err_code = sd_ble_gap_addr_get(&mac_addr);
		APP_ERROR_CHECK(err_code);
	
		mac_addr.addr_type = BLE_GAP_ADDR_TYPE_PUBLIC;
		memcpy(&mac_addr.addr, pu8SrcAddr, sizeof(mac_addr.addr));
		err_code = sd_ble_gap_addr_set(&mac_addr);
		APP_ERROR_CHECK(err_code);
	}
	else
	{
		ret_code = -2;
	}

	return (ret_code);
}

int8_t cod_mac_addr_get(uint8_t * pu8DstAddr)
{
	int8_t ret_code = 0;

	if(pu8DstAddr != NULL)
	{   
        pu8DstAddr[0] = 0x30;
        pu8DstAddr[1] = 0x17;
        pu8DstAddr[2] = 0x45;
        pu8DstAddr[3] = 0xde;
        pu8DstAddr[4] = 0x5d;
        pu8DstAddr[5] = 0xff;
	}
	else
	{
		ret_code = -2;
	}

	return (ret_code);
}

int8_t cod_mac_addr_init(void)
{
    uint8_t mac_arr[6] = {0};
    
	memset((void *)mac_arr, 0, sizeof(mac_arr));
	cod_mac_addr_get(mac_arr);
	cod_mac_addr_set(mac_arr);
    
    return 0;
}

那可以将你的测试工程发到我的邮箱吗？这样我可以对照一下，我这边是哪儿出现了问题。
邮箱是alex_li0824@126.com

**Comment by TuChucheng** [comment]
工程还是一样的工程，只是修改mac地址是在board.c文件的bsp_board_init函数最后调用mible_gap_address_set()。mible_gap_address_set()的实现可参照nRF5_api.c中的mible_gap_address_get实现方法。我的实现如下：
void mible_gap_address_set(void)
{
    uint32_t errno;
    ble_gap_addr_t gap_addr;	
    #if (NRF_SD_BLE_API_VERSION >= 3)
	      errno = sd_ble_gap_addr_get(&gap_addr);
	      gap_addr.addr_type = 0;
	      gap_addr.addr_id_peer = 0;
	      gap_addr.addr[5] &= 0x7F; //Public Device Address
        errno = sd_ble_gap_addr_set(&gap_addr);
    #else
        errno = sd_ble_gap_address_get(&gap_addr);
    #endif
    
    MI_LOG_DEBUG("\nmible_gap_address_set %d\n", errno);
    return;// err_code_convert(errno);
}

**Comment by alex0824li** [comment]
请问一下，在米家APP里面，一个账号（或者说一个手机）同种产品只能对应一个MAC地址，是吗？

**Comment by TuChucheng** [comment]
是的，MAC地址写在广播包里面，重复了就认为是同一设备发出的广播了

**Comment by TuChucheng** [comment]
sorry，我看错了，你说的同种产品，肯定不是相同的。每个设备都可以有单独的MAC。
