### ISSUE TITLE
接入米家协议之后，使用其他非米家APP连接会自动断开

### ISSUE THREAD

**Issue by alex0824li** [MiEcosystem/mijia_ble#17]
在将我的设备增加了米家协议之后，使用非米家APP连接上会出现自动断开，但使用MI家APP连接则不会出现自动断开。我看到网站的介绍说连接上之后未通过验证就会出现断开的情况，但是我们有DA14585方案接入的米家协议之后又没有断开，不知哪个是对的？或者说不知道52832方案的米家demo的非MI家APP连接上会自动断开是正常的？

**Comment by TuChucheng** [comment]
这里提供的只是设备和米家APP认证的demo，没试过使用非米家APP的情况
