### ISSUE TITLE
蓝牙网关上报调试

### ISSUE THREAD

**Issue by sd361541453** [MiEcosystem/mijia_ble#18]
发送广播包(带有联动Object的), 但是一直没有收到相应的动作, 不知道怎么去调试.
userID:424881015
蓝牙网关:Yeelight语音助手
ProductID:0x04E1(蓝牙魔方)
协议格式:申请的时候是这样子申请的.
![image](https://user-images.githubusercontent.com/12649744/58531572-5dbb7080-8215-11e9-9c54-e1504c751f1a.png)
广播内容: 尝试过多种可能的格式.都未能有相应的效果.
![image](https://user-images.githubusercontent.com/12649744/58531478-06b59b80-8215-11e9-80e8-70f65075e1a2.png)
![image](https://user-images.githubusercontent.com/12649744/58531491-1208c700-8215-11e9-9347-52949d2bf13c.png)
![image](https://user-images.githubusercontent.com/12649744/58531719-e76b3e00-8215-11e9-9a84-49de5dffc4a3.png)
智能配置:像手机发送通知.通知是有效的.温度计的通知是可以接收的.
发送时间:本周一直都在发送, 试过100ms, 2000ms
![image](https://user-images.githubusercontent.com/12649744/58531397-bc341f00-8214-11e9-8f66-3df2d4b50596.png)
![image](https://user-images.githubusercontent.com/12649744/58531328-868f3600-8214-11e9-804b-b75d92533337.png)

**Comment by yang325** [comment]
![图片](https://user-images.githubusercontent.com/9655368/58544684-59528000-8234-11e9-97ac-0b923e199a87.png)
箭头所指是frame counter，用于去重，每次按键需确保这个counter递增，这里处理没？

**Comment by sd361541453** [comment]
> ![图片](https://user-images.githubusercontent.com/9655368/58544684-59528000-8234-11e9-97ac-0b923e199a87.png)
> 箭头所指是frame counter，用于去重，每次按键需确保这个counter递增，这里处理没？

ok, 我改一下试试.

**Comment by sd361541453** [comment]
> ![图片](https://user-images.githubusercontent.com/9655368/58544684-59528000-8234-11e9-97ac-0b923e199a87.png)
> 箭头所指是frame counter，用于去重，每次按键需确保这个counter递增，这里处理没？

Nordic版本的MiBeacon貌似默认没加, 自己加一个试了下, 还是没有效果.  

![image](https://user-images.githubusercontent.com/12649744/58662413-b6495580-835c-11e9-986c-99475101fbd3.png)
