### ISSUE TITLE
申请米家蓝牙标准认证库多次未得到回应

### ISSUE THREAD

**Issue by 858876586** [MiEcosystem/mijia_ble#19]
你好，我们希望将公司的单火线蓝牙开关产品接入到小米IOT生态中，前一周已经完成了小米IOT平台的企业开发组的认证，同时也在小米IOT平台新建了对应产品，目前多次通过发送邮件(发送方：858876586@qq.com)申请蓝牙标准认证库都没有得到回应，能够帮忙看看什么原因吗？或者给个其他的联系方式，比如开发支持群之类的？

**Comment by TuChucheng** [comment]
您好！这种问题可能需要贵司的商务或产品人员先与我司对接，谢谢！

**Comment by 858876586** [comment]
请问，这个对接流程有文档描述吗，有的话帮忙发个链接好吗？或者该如何联系贵司人员？之前看开发者平台文档描述直接发送申请邮件就可以的，但我们先前发送的申请邮件没有收到任何回复。




------------------ 原始邮件 ------------------
发件人: "TuChucheng"<notifications@github.com>; 
发送时间: 2019年8月18日(星期天) 中午11:03
收件人: "MiEcosystem/mijia_ble"<mijia_ble@noreply.github.com>; 
抄送: "贝壳"<858876586@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [MiEcosystem/mijia_ble] 申请米家蓝牙标准认证库多次未得到回应 (#19)




您好！这种问题可能需要贵司的商务或产品人员先与我司对接，谢谢！

**Comment by TuChucheng** [comment]
您好！后续有问题请到小米开发者平台个人中心的工地系统中提工单，那里的响应会比较及时，GitHub issue将逐步关闭。谢谢！
