### ISSUE TITLE
LOG关闭后编译失败

### ISSUE THREAD

**Issue by jimyc** [MiEcosystem/mijia_ble#2]
现在使用demo程序在nrf52832 sdk15.2中成功编译后，demo可以正常广播，并且可以被米家app发现，现在我尝试以下步骤关闭log功能
1.在keil MDK的Options for Target 'nrf52832_xxaa'/ C/C++ / Define中将MI_LOG_ENABLED去掉
2.在项目的sdk_config.h中将NRF_LOG_BACKEND_RTT_ENABLED和NRF_LOG_ENABLED关掉

编译后，仍然会出现以下错误
.\_build\nrf52832_xxaa.axf: Error: L6218E: Undefined symbol m_nrf_log_app_logs_data_const (referred from mible_server.o).
.\_build\nrf52832_xxaa.axf: Error: L6218E: Undefined symbol nrf_log_frontend_hexdump (referred from mible_server.o).
.\_build\nrf52832_xxaa.axf: Error: L6218E: Undefined symbol nrf_log_frontend_std_0 (referred from mible_server.o).
.\_build\nrf52832_xxaa.axf: Error: L6218E: Undefined symbol nrf_log_frontend_std_1 (referred from mible_server.o).
.\_build\nrf52832_xxaa.axf: Error: L6218E: Undefined symbol nrf_log_frontend_std_2 (referred from mible_server.o).
.\_build\nrf52832_xxaa.axf: Error: L6218E: Undefined symbol nrf_log_frontend_std_3 (referred from mible_server.o).

另外，如果只修改上面的步骤1，而将sdk_config.h中的LOG功能打开，发现log仍然会正常输出，请问如需关掉log功能，是否还需要做其他处理，谢谢！
附keil版本号：
    Toolchain：MDK-ARM Plus Version：5.23
    C Complier：V5.06 update4（build 422）

**Comment by TuChucheng** [comment]
按照步骤1，是可以关掉应用层中以MI_LOG_开头的函数打印的log的；步骤2暂时还没涉及到。

**Comment by jimyc** [comment]
你好！我反复进行了很多次尝试，编译还是失败的，您有什么建议？在nrf52832 sdk15.2上开发，相应的API和lib下载路径是那个？我想确认下是否api和lib的文件下载的有问题，谢谢！

**Comment by TuChucheng** [comment]
你之前可以跑起来，证明API或者lib是没有问题。你现在只是要解决关log的问题吧？我刚试了一下，只需要在sdk_config.h中将7424行改为#define NRF_LOG_ENABLED 0 就可以关掉所有log，并无编译错误。

**Comment by jimyc** [comment]
你好！跟您确认一下，mible_app_authen下面的lib文件应该是那个版本？我有收到两个文件，我的项目不需要WIFI，只有BLE并且没有IIC，是需要选择其中一个文件还是需要两个文件共同使用？

**Comment by TuChucheng** [comment]
请问你收到的两个lib的文件名？nrf52832 sdk15.2对应的认证库版本号应该是1.1.3

**Comment by jimyc** [comment]
您好！我收到的两个lib文件的文件名为mijia_std_authen_keil_nrf52_1_1_3_8f564473和mijia_std_authen_keil_nrf52_1_1_3_783df025，谢谢！

**Comment by TuChucheng** [comment]
用比较新的mijia_std_authen_keil_nrf52_1_1_3_783df025

**Comment by jimyc** [comment]
你好！我重新下载了mijia_ble下的代码，直接将其放入SDK路径下，只是做了以下修改：
1.将sdk_config.h的7424行#define NRF_LOG_ENABLED 0，
2.keil MDK的Options for Target 'nrf
52832_xxaa'/ C/C++ /Preprocessor Symbols中去掉MI_LOG_ENABLED
做了以上修改后还是会出现以下错误，请帮忙您那边和我这边的测试环境是否一致，感谢！
SDK版本：nRF5_SDK_15.2.0_9412b96
验证库文件：mijia_std_authen_keil_nrf52_1_1_3_783df025
keil MDK版本：V5.23
错误信息：
`.\_build\nrf52832_xxaa.axf: Error: L6218E: Undefined symbol m_nrf_log_app_logs_data_const (referred from mible_server.o).
.\_build\nrf52832_xxaa.axf: Error: L6218E: Undefined symbol nrf_log_frontend_hexdump (referred from mible_server.o).
.\_build\nrf52832_xxaa.axf: Error: L6218E: Undefined symbol nrf_log_frontend_std_0 (referred from mible_server.o).
.\_build\nrf52832_xxaa.axf: Error: L6218E: Undefined symbol nrf_log_frontend_std_1 (referred from mible_server.o).
.\_build\nrf52832_xxaa.axf: Error: L6218E: Undefined symbol nrf_log_frontend_std_2 (referred from mible_server.o).
.\_build\nrf52832_xxaa.axf: Error: L6218E: Undefined symbol nrf_log_frontend_std_3 (referred from mible_server.o).
Not enough information to list image symbols.`

**Comment by TuChucheng** [comment]
1、你先回退到之前可以编译成功的状态（我猜测是因为你的SDK中的sdk_config.h文件被改动了）；
2、只改动：sdk_config.h中将7424行改为#define NRF_LOG_ENABLED 0 就可以关掉所有log。

**Comment by jimyc** [comment]
你好！我反复试了几遍，确定sdk_config.h中已将#define NRF_LOG_ENABLED 0，仍然出现上面的编译错误。

**Comment by TuChucheng** [comment]
#define NRF_LOG_ENABLED 1 的时候能够编译成功？

**Comment by jimyc** [comment]
是的，只修改#define NRF_LOG_ENABLED 1就可以编译成功。

**Comment by TuChucheng** [comment]
重新编译了一个关掉log的认证库mijia_std_authen_keil_nrf52_1_1_3_1cce58ac_NoLog.lib，麻烦再按之前的流程申请一下
