### ISSUE TITLE
02D wifi模块OTA升级遇到两个问题 

### ISSUE THREAD

**Issue by xiaoyongge** [MiEcosystem/mijia_ble#20]
问题一：
![image](https://user-images.githubusercontent.com/12733226/60147328-824c3d80-97ff-11e9-8532-ba039b3c6cce.png)
![image](https://user-images.githubusercontent.com/12733226/60147332-85dfc480-97ff-11e9-9803-62837aa2f4d4.png)

文档里写调用update_me返回ok/error，但是log返回的是todo。硬件02D wifi模块。
问题二：
![image](https://user-images.githubusercontent.com/12733226/60147341-8d06d280-97ff-11e9-88bb-d931cb66d193.png)
![image](https://user-images.githubusercontent.com/12733226/60147358-a7d94700-97ff-11e9-8435-cf8bbf4ed9cf.png)

通过后台OTA升级在30%进度失败了，30%进度是具体哪个位置

**Comment by TuChucheng** [comment]
这里是米家BLE标准认证demo的工程，麻烦到您遇到问题对应的工程下提issue
