### ISSUE TITLE
52810-S112-闭源库宏定义不相容.

### ISSUE THREAD

**Issue by sd361541453** [MiEcosystem/mijia_ble#21]
按说明命令行克隆工程下来然后加入lib文件,然后编译出现一些错误.不知道是不是需要更新Lib文件.
![image](https://user-images.githubusercontent.com/12649744/61000138-53050700-a38f-11e9-9dd3-fd0687df5ea1.png)

**Comment by TuChucheng** [comment]
52810关掉了FPU，需要重新申请认证库

**Comment by sd361541453** [comment]
ok
