### ISSUE TITLE
nrf52810连接米家APP，512810重启后异常断连

### ISSUE THREAD

**Issue by EggplantPotatoes** [MiEcosystem/mijia_ble#22]
米家APP可以顺利扫到设备并添加到米家平台上，设备添加之后米家插件可以正常连接，但是一旦设备重启之后，米家插件就连接上之后就自动断开；但是重新将米家APP中的设备删除，重新添加之后就有可以正常连接；感觉像是固件上的bug，还请协助

**Comment by TuChucheng** [comment]
麻烦发一下异常时候的log

**Comment by EggplantPotatoes** [comment]
![QQ截图20190716103058](https://user-images.githubusercontent.com/50572578/61261672-1da85100-a7b5-11e9-94d3-be2e4a047eb1.png)

**Comment by TuChucheng** [comment]
看log现象，是认证成功，但是相关的认证数据没有存储，所以到了登陆流程，验证认证数据失败，所以登陆失败。不知道你们在代码中修改了什么，建议关注一下红色的error问题

**Comment by EggplantPotatoes** [comment]
您好，我使用原版的米家52810 project 只修改pid = 1342 其他不做任何操作，也出现同样的现象，如下
![image](https://user-images.githubusercontent.com/50572578/61263437-695df900-a7bb-11e9-9805-9f42fb1f1c9f.png)
是否还有其他的地方我还没有注意到呢？

**Comment by TuChucheng** [comment]
这里的PSM初始化成功，但是绑定失败了。请问不修改pid，用最原始的，可以绑定成功吗？对比log看一下

**Comment by EggplantPotatoes** [comment]
请问不修改pid，我在添加设备的界面应该选择呢个设备呢？添加界面无法扫描到我的设备啊！

**Comment by TuChucheng** [comment]
设备名称叫小米蓝牙开发板。如果看不到，发我小米账号，给你开白名单

**Comment by EggplantPotatoes** [comment]
1058089190

**Comment by TuChucheng** [comment]
已添加，10分钟左右生效，到时候再试一下

**Comment by EggplantPotatoes** [comment]
您好，有测试过，小米蓝牙开发板也有同样的问题，如下：
1、添加小米蓝牙开发板至米家APP，可以绑定成功，log如下：
![认证绑定](https://user-images.githubusercontent.com/50572578/61265763-58fe4c00-a7c4-11e9-99bc-36b860f51c3b.png)
2、第一次进入之后连接小米蓝牙开发板，可以正常控制，手机界面面如下：
![初次正常控制](https://user-images.githubusercontent.com/50572578/61265894-fe192480-a7c4-11e9-89a8-f77059cadfcd.png)
3、将蓝牙板重启，依然会出现红色的log信息：
![重启异常](https://user-images.githubusercontent.com/50572578/61265997-6a942380-a7c5-11e9-9d64-12d3b500fe80.png)
4、再次进入米家蓝牙开发板设备连接，一直连接不上，且开发板一直没有连接成功的log打出
![再次进入连接不正常](https://user-images.githubusercontent.com/50572578/61266335-fc9c2c00-a7c5-11e9-8e02-8cb9c1778167.png)

**Comment by TuChucheng** [comment]
十分抱歉，是我们这边的问题，Demo中误删了一些东西。麻烦再更新一下main.c文件，或者直接在services_init();之前加上一句mible_record_create(0xBEEF,0);
