### ISSUE TITLE
设备重置需要调用哪个接口？

### ISSUE THREAD

**Issue by pengchengcool** [MiEcosystem/mijia_ble#23]

**Comment by pengchengcool** [comment]
你好，这边尝试调用nortic重置操作，但是调用之后和米家的app还是有绑定关系，请问下米家这边有没有提供重置操作的接口？

**Comment by TuChucheng** [comment]
在米家APP上将设备删除就行了

**Comment by pengchengcool** [comment]
已经在米家上把设备删除了，但是重新绑定设备的时候提示设备已被绑定，说明应该是设备没有重置。

**Comment by TuChucheng** [comment]
调用mible_std_auth_factory_reset 删除米家认证相关数据，将设备恢复至出厂状态

**Comment by pengchengcool** [comment]
你好，我们接入的锁，是高级ble接入模式（安全级别比较高），里面没有你说的mible_std_auth_factory_reset这个接口。

**Comment by TuChucheng** [comment]
噢噢 这样 那请麻烦到mijia_ble_secure下提issue，对于锁的接入我也不太懂

**Comment by pengchengcool** [comment]
好的 谢谢！！
