### ISSUE TITLE
米家SDK添加之后其他APP timer工作出现异常？

### ISSUE THREAD

**Issue by alex0824li** [MiEcosystem/mijia_ble#24]
我这边使用的是lib版是mijia_std_authen_keil_nrf_1_1_4_752fc700.lib。
问题描述：
**在不添加米家功能之前可以使用10个以上的APPTIMER，并且工作很稳定，但是在添加了米家功能之后，就出现了部分APPTIMER工作不正常的情况，不是必现，但是长时间测试会出现问题。**
测试的时候将我原来的APPTIMER使用个数减少之后，系统剩下的功能能正常工作，不知为何？APPTIMWER的使用最大个数在原来的基础上增加了15，问题依旧存在，

**Comment by TuChucheng** [comment]
您好！这版认证库已经发布很长时间，没有听到类似的问题反馈，我们也没办法复现问题。如有技术支持需求，请先联系我司产品经理。谢谢！

**Comment by TuChucheng** [comment]
您好！后续有开发问题请到小米开发者平台个人中心的工地系统中提工单，GitHub issue将逐步关闭。谢谢！
