### ISSUE TITLE
插件和硬件连接时token交换出现问题

### ISSUE THREAD

**Issue by badsdy** [MiEcosystem/mijia_ble#3]
我们在测试的过程中发现有时候插件和硬件无法连接，而且一旦出现这个问题，硬件和插件就再也无法连接上，除非在米家中删除设备，然后重新绑定。我们已经提交了一个issue（https://github.com/MiEcosystem/mijiaSDK/issues/18）给插件的同学。结论是“app发送加密token后，没有收到设备返回的notify” 。想问一下这个可能是什么问题，如何debug和输出log。
如何复现这个问题：米家新绑定一个设备，第一次进入插件如果连接不上（提示连接超时），以后每次连接(无论用iOS还是安卓)都无法建立连接并提示连接超时。第一次进入插件连接不上不是必现。

**Comment by TuChucheng** [comment]
可以在工程编译选项中加上MI_LOG_ENABLED，打开log信息看一下认证的流程

**Comment by TuChucheng** [comment]
已经有一段时间没收到您的反馈，应该是问题已解决，关闭此issue
