### ISSUE TITLE
IAR8.22.1编译ST-BLUENRG-132错误

### ISSUE THREAD

**Issue by 15867485359** [MiEcosystem/mijia_ble#4]
蓝牙芯片：ST-BLUENRG-132
开发环境，IAR 8.22.1
SDK环境：sdk2.6.0
LIB文件：mijia_std_authen_IAR_BLUENRG-1_1_1_2.a

错误1：
Error[Li006]: duplicate definitions for "mible_service_init_cmp"; in "D:\Program Files (x86)\STMicroelectronics\BlueNRG-1_2 DK 2.6.0\Project\BLE_Examples\mijia_ble-ST\demos\BlueNRG-X\mible_std_authen\EWARM\BlueNRG-1\ 
Server\Obj\BLE_Chat_main.o", and "mible_server.o(mijia_std_authen_IAR_BLUENRG-1_1_1_2.a)" 

警告1：
Warning[Lt009]: Inconsistent wchar_t size 
acl_list.o(libbluenrg1_stack.a) and 3 other objects have wchar_t size 16 bits 
BLE_Chat_main.o and 61 other objects, some of them in mijia_std_authen_IAR_BLUENRG-1_1_1_2.a and 26 other libraries have wchar_t size 32 bits

**Comment by TuChucheng** [comment]
可申请最新的认证库，1_1_2版本可能存在此问题
