### ISSUE TITLE
米家sdk占用timer资源？

### ISSUE THREAD

**Issue by wudide0725** [MiEcosystem/mijia_ble#5]
我方一个应用用到了timer（timer做pwm使用），能正常运行在官方sdk的基础上，但是加入了米家相关的sdk后，在此调用timer相关的应用不能运行了，麻烦各位帮助解答一下，另外时候还有其他的资源占用情况，帮忙提供一下。

**Comment by yuanxing-THU** [comment]
mijia_ble/demos/XXXX/portable 下是各个平台适配米家接口的实现。 接口里有flash和timer相关。 具体接口详见https://github.com/MiEcosystem/mijia_ble_api 工程
