### ISSUE TITLE
增加米家服务后，数据通信过程时间长

### ISSUE THREAD

**Issue by easy-x** [MiEcosystem/mijia_ble#6]
芯片：nrf52832
SDK：15.2，12.3
SD_Version：S132
problem：
目前在增加米家服务后，我们的数据通信协议是基于蓝牙串口，经过调试，通过蓝牙串口传输的数据米家服务底层这边都会做处理，在连接上设备，我们进行私有协议数据通信，通过LOG信息反映，在连接成功时，米家服务会做一些鉴权类似的验证操作，然后处理通过蓝牙串口接收到的数据，等米家服务底层的接口处理完成后，在进行牙刷内部的协议数据处理。整个过程大概在（5S-7S）左右。去除米家服务后，进行私有协议数据通信。整个过程在800ms左右。请问下增加米家服务的整个过程时长能否减少

**Comment by TuChucheng** [comment]
您好！后续有开发问题请到小米开发者平台个人中心的工地系统中提工单，GitHub issue将逐步关闭。谢谢！
