### ISSUE TITLE
LOG关闭后编译失败

### ISSUE THREAD

**Issue by easy-x** [MiEcosystem/mijia_ble#7]
芯片：nrf52832
SDK：15.2，12.3
SD_Version：S132
problem：
1、能否提供不带LOG的.lib文件，目前提供的.lib文件必须打开LOG模块，在这种情况下我们这边的软件程序大小偏大。
SDK12.3：mijia_std_authen_keil_nrf52_1_1_2.lib
SDK15.2:   mijia_std_authen_keil_nrf52_1_1_3_8f564473.lib

**Comment by TuChucheng** [comment]
问题已解决，关闭此issue
