### ISSUE TITLE
SDK是否兼容DA14580，如果适配DA14585使用内置OTP资源是否满足,不想外挂Flash的话

### ISSUE THREAD

**Issue by guevaraya** [MiEcosystem/mijia_ble#8]
我们调查DA14585 比DA14580资源上多一些，但考虑成本我们期望采用 DA14580适配SDK，请帮忙确认是否可行：
以下是l两个片子的差异，主要是

芯片| OTP |  BLE  | ROM | RAM|
-|-|-|-|-
DA14580 | 32kB | 11 | 84kB | 50kB|
DA14585 | 64kB | 5.0 core | 128kB | 96kB|

![image](https://user-images.githubusercontent.com/446973/56480625-7ab1a500-64ed-11e9-8f97-28d79883e986.png)
![image](https://user-images.githubusercontent.com/446973/56480636-856c3a00-64ed-11e9-8bc5-b8ca287cf2ce.png)

**Comment by TuChucheng** [comment]
具体可咨询芯片原厂，目前开放的是已适配完成的
