### ISSUE TITLE
编译的时候提示缺少文件。

### ISSUE THREAD

**Issue by huangminlakers** [MiEcosystem/mijia_ble#9]
![image](https://user-images.githubusercontent.com/50003976/56785090-2af11780-6826-11e9-978a-9439a6ad9f45.png)
编译的时候提示缺少图片中文件？

**Comment by TuChucheng** [comment]
请参照README中所述，使用git命令类似于git clone -b Nordic --recursive https://github.com/MiEcosystem/mijia_ble.git
直接下载源码包确实是没有的，这些源码是作为submodule链接到此仓库的

**Comment by huangminlakers** [comment]
现在SDK中提示还缺少这个文件mijia_std_authen_keil_nrf52_1_1_2.lib,请问下能不能提供？

**Comment by TuChucheng** [comment]
请参照README中所述：米家蓝牙标准认证库闭源，请联系 https://iot.mi.com/ 平台申请，详见https://iot.mi.com/guide.html#id=57

**Comment by 858876586** [comment]
> 请参照README中所述：米家蓝牙标准认证库闭源，请联系 https://iot.mi.com/ 平台申请，详见https://iot.mi.com/guide.html#id=57

你好，我们这边发送了2次申请这个认证库没有收到任何回应，能帮忙看看什么原因吗？申请方是858876586@qq.com
